# Custom Language File for Launcher Customizer

[ejs.app]
title = "IDIOTSS Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/I-D-I-O-T-S-S/IDIOTSSLauncher/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/I-D-I-O-T-S-S/IDIOTSSLauncher/"
supportLink = "https://github.com/I-D-I-O-T-S-S/IDIOTSSLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE IDIOTSS SERVER"
welcomeDescription = "This is a very cool and awesome server but you probably already know that"
welcomeDescCTA = "Okay now go join the server"
